// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "contato-inicial",
    columns: [
      {
        name: "nome",
        type: "string",
        notNull: true,
        defaultValue: "Nome completo",
      },
      {
        name: "email",
        type: "email",
        notNull: true,
        defaultValue: "Email@provedor.com",
      },
      { name: "telefone", type: "string" },
      { name: "assunto", type: "string" },
      {
        name: "mensagem",
        type: "text",
        notNull: true,
        defaultValue: "Mensagem do usuário",
      },
    ],
  },
  {
    name: "inscritos",
    columns: [
      { name: "Data", type: "datetime" },
      { name: "Nome", type: "string" },
      { name: "CPF", type: "string" },
      { name: "Email", type: "string" },
      { name: "Telefone", type: "string" },
      { name: "area", type: "text" },
      { name: "WorkshopSexta", type: "string" },
      { name: "WorkshopDomingo", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ContatoInicial = InferredTypes["contato-inicial"];
export type ContatoInicialRecord = ContatoInicial & XataRecord;

export type Inscritos = InferredTypes["inscritos"];
export type InscritosRecord = Inscritos & XataRecord;

export type DatabaseSchema = {
  "contato-inicial": ContatoInicialRecord;
  inscritos: InscritosRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://nad-ue460p.us-east-1.xata.sh/db/contato",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
